### ISSUE TITLE
Missing attribution for OpenStreetMap

### ISSUE THREAD

**Issue by dieterdreist** [TheMoMStudio/swzpln.de#19]
Your usage of the OpenStreetMap data is not authorized because you are publishing content based on ODbL licenced data without the required attribution. Please fix this as soon as possible.

**Comment by timethy96** [comment]
Thank you very much for bringing this to my attention. I assume you are referring to the maps in the generated files. I will include the generation of an appropriate attribution to the process of making the files as soon as possible.

**Comment by dieterdreist** [comment]
thank you, some guidance can be found here: osm.org/copyright
