### ISSUE TITLE
DXF-Generation slow

### ISSUE THREAD

**Issue by timethy96** [TheMoMStudio/swzpln.de#2]
The reason behind this is, that i am using a big library (maker.js) for the conversion, when only little code would be needed. Therefore I need to extract the function and change it for my own purpose.

**Comment by timethy96** [comment]
well it is not anymore (web-workers), but it is still excessive to load that whole library for the dxf-conversion.

**Comment by Vestibule** [comment]
It also crashes on too big export (tried it on Paris). I guess it depends also on the computer but it should be okay on an i7-16go like I use.
I have no other idea than a backend implementation for the conversion. It should be quite cheap with an AWS Lambda function. But cheap is not free.

**Comment by timethy96** [comment]
The code has to run on the PC of the user. This is a main objective of the project, demonstrating the power of web-services run locally and thus perfectly respecting the privacy of the users.
The main problem is, that there is no library out there for the conversion of OSM-Data to DXF-Format. Even if the conversion is not that complicated, I did not have the time to write a library for that purpose. Thus I am (and please don't laugh at me) currently converting the OSM to SVG to maker.js-Format to then export it to DXF, which is way too cumbersome for any PC...
So actually it would be best to take the appropriate functions from all those libraries and merge them together to one minimal library for that one purpose.

**Comment by Vestibule** [comment]
Indeed, nothing like running locally for privacy (as long as we don't spy on user doing so).
I didn't realize it was that complicated to convert from OSM to SVG right now.
I'm afraid I won't bring much workforce in this domain, I'm a junior when it comes to maps and their formats.

**Comment by timethy96** [comment]
OSM2SVG is not the main problem (and should be working rather well)... the DXF-format is not so well known outside of CAD-using professions, so there are no libraries for it.

**Comment by Vestibule** [comment]
I wanted to write OSM to DXF, sorry.

**Comment by timethy96** [comment]
closed with release v1.00-RC1
complete rewrite of conversion engine
